
export const DATA = [
    {
      id: '0',
      title: 'Panadol',
      description: 'Panadol Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
      image: require('../assets/Panadol-Tablets.png'),
      pharmacy: 'Pharmaplus Machakos',
      amount:'150',
      distance:'14',
      latitude:'-1.286389',
      longitude:'36.817223',
    },
    {
      id: '1',
      title: 'Action Tablets 20s',
      description: 'Action Tablet is a quality Aspirin, Paracetemol & Caffeine combination brand that promises quick relief from that pounding headache, migraine, backache, toothache, rheumatic pain and dysmenorrhea.',
      image: require('../assets/action.png'),
      pharmacy: 'Muisyo Pharmacy',
      amount:'150',
      distance:'5',
      latitude:'-1.522603 ',
      longitude:'37.265983',
    },
    {
      id: '2',
      title: 'Charco',
      description: 'Activated charcoal is a potent natural treatment used to trap toxins and chemicals in the body, allowing them to be flushed out so the body does not reabsorb them. It is made from a variety of sources, but when used for natural healing, it is important to select activated charcoal made from coconut shells or other natural sources.al TabletActivated charcoal is a potent natural treatment used to trap toxins and chemicals in the body, allowing them to be flushed out so the body does not reabsorb them. It is made from a variety of sources, but when used for natural healing, it is important to select activated charcoal made from coconut shells or other natural sources.s is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
      image: require('../assets/charco.png'),
      pharmacy: 'Beryl Pharmacy',
      amount:'570',
      distance:'2',
      latitude:'-1.286389',
      longitude:'36.817223',
    },
    /*{
        id: '3',
        title: 'Virasob',
        description: 'Acyclovir cream is used to treat cold sores (fever blisters; blisters that are caused by a virus called herpes simplex) on the face or lip. Acyclovir is in a class of antiviral medications called synthetic nucleoside analogues. It works by stopping the spread of the herpes virus in the body. Acyclovir does not cure cold sores or genital herpes, does not prevent outbreaks of these conditions, and does not stop the spread of these conditions to other people. Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/virasob.png'),
        pharmacy: 'Linda Pharmacy',
        amount:'300',
        distance:'2',
        latitude:'-1.286389',
        longitude:'36.817223',
      },*/
      {
        id: '4',
        title: 'Anusol Plus HC Suppositories 12s',
        description: 'Anusol Plus HC suppositories are used for symptomatic treatment of internal haemorrhoids and pruritus ani',
        image: require('../assets/Anusol.png'),
        pharmacy: 'Byrons Chemist',
        amount:'900',
        distance:'2',
        latitude:'-1.286389',
        longitude:'36.817223',
      },
      {
        id: '5',
        title: 'Almax Forte Sachets 30s',
        description: 'ALMAX FORTE 1.5 G 24 SACHETS ORAL SUSPENSION Almax Forte 1.5 G 24 Sachets Oral Suspension, indicated for the symptomatic treatment of gastric hyperacidity in adults and adolescents from 12 years of age. Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/Almax.png'),
        pharmacy: 'Helm Pharmaceuticals Ltd',
        amount:'1250',
        distance:'2',
        latitude:'-1.286389',
        longitude:'36.817223',
      },
      {
        id: '6',
        title: 'Ascoril Expectorant 100ml',
        description: 'Ascoril is an expectorant drug that contains Levosalbutamol, Ambroxol and Guaifenesin as its active ingredients.Panadol Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/Ascroil.png'),
        pharmacy: 'Syokimau Pharmacy',
        amount:'225',
        distance:'2',
        latitude:'-1.286389',
        longitude:'36.817223',
      },
      {
        id: '7',
        title: 'Benylin Cold&Flu Day&Night Max Strength Caps 16s',
        description: 'Benylin Day & Night Tablets are used to relieve nasal or sinus congestion with headache, fever and pain which are associated with the cold and flu. Diphenhydramine helps to relieve a runny nose, whilst pseudoephedrine causes the blood vessels in the nasal and sinus passages to contract and narrow, reducing congestion and the production of excess mucus.Paracetamol helps bring down a fever and provide relief from headaches or bodily aches and pains.Panadol Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/Benylin.png'),
        pharmacy: 'Machakos Dispensing Chemist',
        amount:'940',
        distance:'2',
        latitude:'-1.286389',
        longitude:'36.817223',
      },
       {
        id: '8',
        title: 'Betadine Antiseptic Solution 500ml',
        description: 'Betadine Antiseptic solution contains Povidone Iodine 10% w/v which is used to prevent skin infections. It is an antiseptic applied on skin which is infected or is likely to get infected. It works by slowly releasing iodine which kills or prevents the growth of infectious microorganisms. Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/Betadine.png'),
        pharmacy: 'Machakos Dispensing Chemist',
        amount:'1110',
        distance:'2',
        latitude:'-1.286389',
        longitude:'36.817223',
      },
      {
        id: '9',
        title: 'Biofreeze Pain Relieving Gel 59ml',
        description: 'This medication is used to treat minor aches and pains of the muscles/joints (such as arthritis, backache, sprains). Menthol is known as a counterirritant. It works by causing the skin to feel cool and then warm. These feelings on the skin distract you from feeling the aches/pains deeper in your muscles and joints. Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/Biofreeze.png'),
        pharmacy: 'Athusi Pharmacy',
        amount:'735',
        distance:'5',
        latitude:'-1.522603 ',
        longitude:'37.265983',
      },
      {
        id: '23',
        title: 'Calpol Infant Suspension 100ml',
        description: 'Calpol contains Paracetamol 120 mg in each 5 ml. Paracetamol is an antipyretic (fever reliever) and analgesic (pain reliever). It helps in relieving pain of teething, sore throat and fever associated with colds and flu, childhood infections like chicken pox, whooping cough, measles and mumps.action Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/calpol.png'),
        pharmacy: 'Empire Pharmacy',
        amount:'300',
        distance:'5',
        latitude:'-1.522603 ',
        longitude:'37.265983',
      },
      {
        id: '10',
        title: 'Celestamine Tablets 30',
        description: 'Celestamine tablets contain betamethasone and dexchlorpheniramine used for treating conditions which include allergic reactions, respiratory problems, skin conditions, and dermatologic reactions.action Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/celestamine.png'),
        pharmacy: 'Backwell Pharmacy',
        amount:'730',
        distance:'5',
        latitude:'-1.522603 ',
        longitude:'37.265983',
      },
      {
        id: '11',
        title: 'Deep Heat Pain Relief Rub 35g',
        description: 'Deep Heat Heat Rub is a fast acting, non greasy pain relieving cream. The dual action of pain relief + heat provides targeted, warming relief at the site of pain. Deep Heat Heat Rub contains the asprin -like drug methyl salicylate for effective pain relief and warming ingredients that increase blood flow and provide relief from , back pain, sciatica, fibrositis, sprains, bruises and chillblains .Can be used before or after exercise. Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/Deepheat.png'),
        pharmacy: 'Masaku Chemist',
        amount:'275',
        distance:'5',
        latitude:'-1.522603 ',
        longitude:'37.265983',
      },
      {
        id: '12',
        title: 'Dettol Antiseptic 250ml',
        description: 'Dettol product provides all-round family protection against germs and has been recommended by medical professionals for generations. Use Dettol Antiseptic Disinfectant Liquid to kill germs on the skin, help protect against infection from cuts, scratches and insect bites and it can also be used as a household disinfectant on surfaces or in laundry. It can also be used to sterilize wounds. Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/Dettol.png'),
        pharmacy: 'Machakos Park Chemist',
        amount:'650',
        distance:'5',
        latitude:'-1.522603 ',
        longitude:'37.265983',
      },
      {
        id: '13',
        title: 'Hydrogen Peroxide 200ml',
        description: 'Hydrogen peroxide is a chemical compound with the formula H ₂O ₂. In its pure form, it is a very pale blue, clear liquid, slightly more viscous than water. Hydrogen peroxide is the simplest peroxide. It is used as an oxidizer, bleaching agent, and as an antiseptic Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/Hydroperoxide.png'),
        pharmacy: 'Philimar Pharmacy',
        amount:'100',
        distance:'5',
        latitude:'-1.522603 ',
        longitude:'37.265983',
      },
      {
        id: '14',
        title: 'Eno Calcium Antacid Tablets 20s',
        description: 'Eno Calcium Antacid Tablets are effective for the symptomatic treatment of conditions relating to stomach acidity including heartburn. Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/Eno.png'),
        pharmacy: 'Sachem Pharmacy',
        amount:'170',
        distance:'5',
        latitude:'-1.522603 ',
        longitude:'37.265983',
      },
      {
        id: '15',
        title: 'Fastum Gel 2.5% 50g',
        description: 'Fastum gel 50g contains Ketoprofen 2.5% w/w which is used in rheumatic pain and musculoskeletal pain.Fastum Gel is a non-steroidal anti-inflammatory drug (NSAID). It works by blocking the release of certain chemical messengers that cause fever, pain and inflammation (redness and swelling). Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/Fastum.png'),
        pharmacy: 'Belea Pharmacy',
        amount:'800',
        distance:'5',
        latitude:'-1.522603 ',
        longitude:'37.265983',
      },
      {
        id: '16',
        title: 'Flugone Capsules 10s',
        description: 'Flu-Gone capsules is indicated for the relief of symptoms of the common cold and flu like stuffy nose, sneezing, sinus headache, runny nose, chest congestion and fever. It is well tolerated, effective anticatarrhal with analgesic, decongestant and antihistaminic actions. The individual constituents act synergistically or alone to produce the desired pharmacological effects of Flu-Gone. Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/flu-gone.png'),
        pharmacy: 'Imani Pharmacy',
        amount:'130',
        distance:'5',
        latitude:'-1.522603 ',
        longitude:'37.265983',
      },
      {
        id: '17',
        title: 'Kings First Aid Elastoplast 100s',
        description: 'Elastoplast Plastic plasters are suitable for covering all types of smaller wounds.The material is breathable and is water-repellent.The non-stickwound pad protects and cushions the wound.The strong adhesion ensures that the plaster stays in place. Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/kings-elastoplast.png'),
        pharmacy: 'Helima Pharmacy',
        amount:'130',
        distance:'5',
        latitude:'-1.522603 ',
        longitude:'37.265983',
      },
      {
        id: '18',
        title: 'Milk Of Magnesia 200ml',
        description: 'Milk of magnesia is a type of hyperosmotic laxative. This kind of oral laxative works by drawing water to the bowel from nearby tissue. This softens and moistens the stool. It also helps increase bowel activity. Saline, lactulose, and polymer laxatives are the three types of hyperosmotic laxatives. Milk of magnesia is a saline laxative. These kinds of laxatives are also known as “salts.” They’re meant to be fast acting. You can expect to have a bowel movement within six hours of taking milk of magnesia. Lactulose laxatives draw more water to the bowel from surrounding tissue, but they act more slowly than saline types. People use lactulose types for chronic constipation Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/milkmg.png'),
        pharmacy: 'Memusi Pharmacy',
        amount:'980',
        distance:'5',
        latitude:'-1.522603 ',
        longitude:'37.265983',
      },
      {
        id: '19',
        title: 'Mara Moja Tablets 20s',
        description: 'Mara Moja Tablets is indicated in management of mild to moderate aches and pains. These include headaches, menstrual pains, toothaches, backaches, osteoarthritis, or cold/flu aches and pains and to reduce fever. Each Tablet contains Paracetamol BP 200 mg, Aspirin BP 400 mg and Caffeine BP 50 mg. Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/maramoja.png'),
        pharmacy: 'Kathian Pharmacy',
        amount:'130',
        distance:'5',
        latitude:'-1.522603 ',
        longitude:'37.265983',
      },
      {
        id: '20',
        title: 'Optrex Brightening Drops 10ml',
        description: 'Optrex Eye Brightening Drops have been specially designed, using refreshing natural plant extracts and a special whitening agent. They give you dazzling bright eyes in an instant, so your eyes can look and feel their best. Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/optrex.png'),
        pharmacy: 'Hawkers Pride Pharmacy',
        amount:'1010',
        distance:'5',
        latitude:'-1.522603 ',
        longitude:'37.265983',
      },
      {
        id: '21',
        title: 'Strepsils Orange Vitamin C Lozenges 36s',
        description: 'Strepsils Orange with Vitamin C 100mg are Orange flavoured and coloured circular lozenge.Qualitative and quantitative composition: Amylmetacresol BP 0.6mg, 2.4-Dichlorobenzyl Alcohol HSE 1.2mg Vitamin C, (Ascorbic Acid, Sodium Ascorbate Equivalent to EP) 100.0mg.Therapeutic indications: For the symptomatic relief of mouth and throat infections. Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/strepsils.png'),
        pharmacy: 'Vicdel Pharmacy',
        amount:'970',
        distance:'5',
        latitude:'-1.522603 ',
        longitude:'37.265983',
      },
      {
        id: '22',
        title: 'Vicks Vaporub Jar 50g',
        description: 'Vicks® VapoRub™ Topical Cough Suppressant is appropriate for ages two and above. It is a topical cough medicine with medicated vapors. It starts working quickly for adults as well to relieve cough symptoms. Vicks VapoRub gives you 8 hours of relief from cough and cold so you can enjoy a full night of restful sleep, even with a cold. Don’t let cough and cold come in the way of you and your family’s sweet dreams. Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/vicks.png'),
        pharmacy: 'Thwake Pharmacy',
        amount:'800',
        distance:'5',
        latitude:'-1.522603 ',
        longitude:'37.265983',
      },
      {
        id: '24',
        title: 'Zovirax Cold Sore Cream 2gVicks Vaporub Jar 50g',
        description: 'Zovirax is used for the treatment of cold sores. The active ingredient is aciclovir, an antiviral agent. Apply at the first signs of a cold sore (such as tingling and itching). It can also be used to speed up healing if one has already appeared.Vicks® VapoRub™ Topical Cough Suppressant is appropriate for ages two and above. It is a topical cough medicine with medicated vapors. It starts working quickly for adults as well to relieve cough symptoms. Vicks VapoRub gives you 8 hours of relief from cough and cold so you can enjoy a full night of restful sleep, even with a cold. Don’t let cough and cold come in the way of you and your family’s sweet dreams. Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains, dysmenorrhoea, sore throat, and for relieving the fever.',
        image: require('../assets/zovirax.png'),
        pharmacy: 'Thwake Pharmacy',
        amount:'1200',
        distance:'5',
        latitude:'-1.522603 ',
        longitude:'37.265983',
      },
  ];